#!/bin/bash
# Get the absolute directory of where this script is located
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

# Execute using the venv python interpreter and forward all command-line arguments ($@)
"$SCRIPT_DIR/venv/bin/python" -u "$SCRIPT_DIR/conductor.py" "$@"
